---

- name: "determine path to libjemalloc shared object"
  when: ansible_os_family == "RedHat"
  shell: >
    /usr/bin/rpm --query --list jemalloc |
    /usr/bin/grep --extended-regexp --only-matching --line-regexp --max-count=1
    '^/[_/[:alnum:]-]+/libjemalloc\.so\.1$'
  register: libjemalloc_redhat
  always_run: True
  changed_when: False

- name: "determine path to libjemalloc shared object"
  when: ansible_os_family == "Debian"
  shell: >
    /usr/bin/dpkg --listfiles libjemalloc1 |
    /bin/grep --extended-regexp --only-matching --line-regexp --max-count=1
    '^/[_/[:alnum:]-]+/libjemalloc\.so\.1$'
  register: libjemalloc_debian
  always_run: True
  changed_when: False

- name: "set path to libjemalloc shared object"
  when: ansible_os_family == "RedHat"
  set_fact:
    libjemalloc: "{{ libjemalloc_redhat.stdout }}"
  always_run: True
  changed_when: False

- name: "set path to libjemalloc shared object"
  when: ansible_os_family == "Debian"
  set_fact:
    libjemalloc: "{{ libjemalloc_debian.stdout }}"
  always_run: True
  changed_when: False

- name: "install /usr/local/bin/discourse-unicorn-reload.sh"
  copy:
    src: "discourse-unicorn-reload.sh"
    dest: "/usr/local/bin/discourse-unicorn-reload.sh"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "install discourse-unicorn-env"
  template:
    src: "discourse-unicorn-env.j2"
    dest: "{{ sysconfig_directory }}/discourse-unicorn-env"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "restart discourse-unicorn"

- name: "install /var/www/discourse/config/unicorn.rb"
  template:
    src: "unicorn.rb.j2"
    dest: "/var/www/discourse/config/unicorn.rb"
    owner: "discourse"
    group: "discourse"
    mode: "0644"

- name: "install unicorn shim"
  copy:
    src: "unicorn"
    dest: "/usr/local/{{ libexecdir }}/unicorn"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "install discourse-unicorn.service"
  template:
    src: "discourse-unicorn.service.j2"
    dest: "/etc/systemd/system/discourse-unicorn.service"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "restart discourse-unicorn"

- name: "systemctl daemon-reload"
  command: "/bin/systemctl daemon-reload"
  changed_when: False

- name: "enable discourse-unicorn.service"
  service:
    name: "discourse-unicorn.service"
    enabled: True

- name: "start discourse-unicorn.service"
  service:
    name: "discourse-unicorn.service"
    state: "started"
  register: start_discourse_unicorn

- name: "wait for discourse-unicorn.service to start"
  when: start_discourse_unicorn.changed
  pause:
    seconds: "15"

