---

- name: "install pg_hba.conf"
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgres_configs }}/pg_hba.conf"
    owner: "postgres"
    group: "postgres"
    mode: "0600"

- name: "install postgresql.conf"
  template:
    src: "postgresql.conf.j2"
    dest: "{{ postgres_configs }}/postgresql.conf"
    owner: "postgres"
    group: "postgres"
    mode: "0600"

