---

- name: "install packages"
  apt:
    name: "{{ item }}"
    default_release: "jessie-pgdg"
    state: "present"
  with_items:
    - "postgresql-{{ postgres_version }}"
  register: install_postgresql

- name: "drop default cluster"
  when: install_postgresql.changed
  command: "/usr/bin/pg_dropcluster --stop {{ postgres_version }} main"

- name: "install packages"
  apt:
    name: "{{ item }}"
    default_release: "jessie-pgdg"
    state: "present"
  with_items:
    - "postgresql-client-{{ postgres_version }}"
    - "postgresql-contrib-{{ postgres_version }}"
    - "postgresql-server-dev-{{ postgres_version }}"
    - "python-psycopg2"

