---

nginx_worker_processes:       "1"

# worker_connections cannot exceed the OS limit for open file descriptors.
nginx_worker_connections:     "4096"
nginx_limit_nofile:           "16384"

nginx_charset:                "utf-8"
nginx_keepalive_timeout:      "60s"
nginx_server_tokens:          "off"
nginx_sendfile:               "on"
nginx_tcp_nopush:             "on"
nginx_tcp_nodelay:            "on"
nginx_types_hash_max_size:    "2048"

nginx_gzip:                   True
nginx_gzip_comp_level:        "1"
nginx_gzip_min_length:        "1000"
nginx_gzip_types:             "text/css application/x-javascript application/javascript application/json"

nginx_ratelimit_enabled:      True
nginx_reqs_per_second:        "12"
nginx_bursts_per_second:      "12"
nginx_reqs_per_minute:        "200"
nginx_bursts_per_minute:      "100"

# Maximum file upload size.
nginx_client_max_body_size:   "10m"

# Enable this to protect against hotlinking.
nginx_check_referer:          False
nginx_valid_referers:         "none blocked {{ discourse_hostname }}"

# See <docs/README.headers.rst> for help on browser security.
response_headers:
  - 'X-UA-Compatible "IE=edge"'

# http://nginx.org/en/docs/http/ngx_http_realip_module.html#set_real_ip_from
# Comma-separated list of trusted addresses. Useful if behind a proxy.
nginx_set_real_ip_from:       []

#-----#
# TLS #
#-----#

# See <docs/README.https.rst> for instructions on how to configure TLS.
tls_enabled:                  False

#tls_response_headers:
#  - 'Strict-Transport-Security "max-age=15768000"'

tls_dhparam_size:             "2048"
nginx_ssl_session_timeout:    "10m"
nginx_ssl_session_cache:      "10m"
nginx_ssl_buffer_size:        "16k"

spdy_enabled:                 True
nginx_spdy_keepalive_timeout: "3m"
nginx_spdy_headers_comp:      "6"

# Concatenate the CA root and intermediate certificates to create the bundle.
# OCSP will not work without this.
tls_ocsp_stapling_enabled:    False
tls_ca_bundle:                "files/pki/ExampleCA.bundle.pem"
nginx_resolver:               "127.0.0.1"
nginx_resolver_timeout:       "5s"

# https://wiki.mozilla.org/Security/Server_Side_TLS
tls_protocols:                "TLSv1 TLSv1.1 TLSv1.2"
tls_ciphers:                  "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA"

